### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by bartostefan** [hoetmaaiers/url2png-gem#20]
Please update documentation. 

When i use method: url2png_image_url in my controller, i must include Url2png::Helpers::Common into controller. I was looking for this solution 20 minutes :-)

Thank you and GJ

**Comment by sergiotapia** [comment]
@hoetmaaiers @xostudio  How can I use the `url2png_image_url` method inside my model? I want to run a rake task to update the screenshot for multiple records.

**Comment by hoetmaaiers** [comment]
I am afraid this is not possible at the moment ...

**Comment by CodyFitzpatrick** [comment]
@hoetmaaiers Is it possible to run `url2png_image_url` via a worker/background job or even via `rails console`? I ask because I'm having trouble despite `require 'Url2png'`'ing.

**Comment by hoetmaaiers** [comment]
Not sure if this is possible @CodyFitzpatrick , I stopped using this gem a long while ago in all honesty. If anyone is willing to take over ownership of the gem please let me know. Until then, this gem will stay what it is at the moment...

**Comment by CodyFitzpatrick** [comment]
I appreciate the response @hoetmaaiers. As much as I wanted to use the gem, I too had to abandon it after it failed to perform properly in a few scenarios, Sidekiq background workers included.

[URL2PNG's Ruby documentation](https://www.url2png.com/docs) ultimately led me to a working solution that utilizes background workers.

I completely understand your attitude toward its maintenance -- priorities!

**Comment by hoetmaaiers** [comment]
Thank you for the response. Maybe this thread can steer people with the similar issues in the right direction.
