### ISSUE TITLE
The 'unique' param should be allowed

### ISSUE THREAD

**Issue by jagthedrummer** [hoetmaaiers/url2png-gem#22]
The `unique` param allows you to encourage the service to take a new screenshot or to reuse an old one for a period of time. It's documented here: https://www.url2png.com/docs

When I try to use it an exception is raised:

> "unique" is not a valid option ↵Check the gem homepage for information about options: https://github.com/robinhoudmeyers/url2png-gem

**Comment by hoetmaaiers** [comment]
The unique parameter is indeed not available. It shouldn't be to hard to include this parameter. You can provide a pull request which implements this option.

**Comment by jacquescrocker** [comment]
maybe here? https://github.com/Simplero/url2png-gem/commit/83f34f2a9436460d975ed732bbb80042df0f662e

**Comment by hoetmaaiers** [comment]
Wanna send a pull request?

**Comment by jagthedrummer** [comment]
This was fixed in #23
